language: node_js

node_js:
  - node
  - lts/*

sudo: false

branches:
  only:
    - master
    - dev

# use newer version of yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache: yarn

script:
  - yarn run test-ci
  - codecov
